---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "deploying Backend Database"
spec:
  selector:
    matchLabels:
      app: application
  template: 
    metadata:
      labels:
        app: application
    spec:
      containers: 
      - name: app-container
        image: anildoc143/privaterepo_websites:app
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
          limits:
            cpu: "500m"
            memory: "600Mi"
      imagePullSecrets:
      - name: mydockerhub-secret

    
              
