---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "deploying Backend Database"
spec:
  selector:
    matchLabels:
      app: application
  template: 
    metadata:
      labels:
        app: application
    spec:
      containers: 
      - name: app-container
        image: anildoc143/privaterepo_websites:app
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "350Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 2
      imagePullSecrets:
      - name: mydockerhub-secret

    
              
