---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-container
          image: anildoc143/privaterepo_websites:db           # Optional: specify a version
          ports:
            - containerPort: 3306
          resources:
              requests:
                cpu: "500m"
                memory: "1Gi"
              limits:
                cpu: "2"
                memory: "2Gi"
          volumeMounts:
          - name: db-data
            mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          hostPath: 
            path: /data/db
      imagePullSecrets:
        - name: mydockerhub-secret
