---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "deploying Backend Database"
spec:
  selector:
    matchLabels:
      app: db
  template: 
    metadata:
      labels:
        app: db
    spec:
      containers: 
      - name: db-container
        image: anildoc143/privaterepo_websites:db
        ports:
          - containerPort: 3306
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "350Mi"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 30
      imagePullSecrets:
        - name: mydockerhub-secret

    
              
