---
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minkube_jenkins
  namespace: dev
rolebindings:
- kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: default  

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: dev
type: kubernetes.io/service-account-token
data:
  annotations:
    kubernetes.io/service-account.name: "jenkins"
